Patch Iterator Optimization Error
Optimizing the SQL iterator with certian queries raises the following errors:

ERROR: Couldn't get cursor from SQL database: pq: syntax error at or near ";"
ERROR: Couldn't make query: pq: syntax error at or near ";"

This looks to be due to a bare HasA. This commit is a quick patch to avoid the
SQL syntax error, with a big comment explaining that the problem may be deeper.